# Generated by Django 2.2.11 on 2020-06-17 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chanpincenter', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShareExample',
        ),
        migrations.DeleteModel(
            name='ShareExampleCategory',
        ),
    ]
