# Generated by Django 2.2.11 on 2020-04-26 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datacenter', '0003_auto_20200426_1719'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='account',
            unique_together={('date', 'userid')},
        ),
    ]
