# Generated by Django 2.2.11 on 2020-04-27 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacenter', '0004_auto_20200426_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='日期'),
        ),
    ]
