# Generated by Django 2.2.11 on 2020-04-27 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacenter', '0006_auto_20200427_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='date',
            field=models.DateField(verbose_name='日期'),
        ),
        migrations.AlterField(
            model_name='account',
            name='userid',
            field=models.IntegerField(verbose_name='账户ID'),
        ),
    ]
