# Generated by Django 2.2.11 on 2020-04-27 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacenter', '0007_auto_20200427_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='userid',
            field=models.CharField(max_length=16, verbose_name='账户ID'),
        ),
        migrations.AlterField(
            model_name='feed',
            name='userid',
            field=models.CharField(max_length=16, verbose_name='账户ID'),
        ),
        migrations.AlterField(
            model_name='otherpro',
            name='userid',
            field=models.CharField(max_length=16, verbose_name='账户ID'),
        ),
        migrations.AlterField(
            model_name='total',
            name='userid',
            field=models.CharField(max_length=16, verbose_name='账户ID'),
        ),
    ]
