# Generated by Django 2.2.11 on 2020-04-27 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacenter', '0008_auto_20200427_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='signup_date',
            field=models.DateTimeField(verbose_name='开户日期'),
        ),
    ]
