# Generated by Django 2.2.11 on 2020-04-27 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacenter', '0009_auto_20200427_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='allbalance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='推广总余额'),
        ),
    ]
