# Generated by Django 2.2.11 on 2020-04-27 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacenter', '0010_auto_20200427_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='signup_date',
            field=models.DateField(verbose_name='开户日期'),
        ),
    ]
