# Generated by Django 2.2.11 on 2020-04-27 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacenter', '0011_auto_20200427_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='is_rebate',
            field=models.CharField(max_length=8, verbose_name='是否高返'),
        ),
    ]
