# Generated by Django 2.2.11 on 2020-04-28 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacenter', '0012_auto_20200427_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='signup_date',
            field=models.DateField(blank=True, null=True, verbose_name='开户日期'),
        ),
    ]
