# Generated by Django 2.2.11 on 2020-04-28 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacenter', '0013_auto_20200428_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='total',
            name='account_indus_1',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='账户一级行业'),
        ),
        migrations.AddField(
            model_name='total',
            name='account_indus_2',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='账户二级行业'),
        ),
        migrations.AlterField(
            model_name='total',
            name='customer_indus_1',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='客户一级行业'),
        ),
        migrations.AlterField(
            model_name='total',
            name='customer_indus_2',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='客户二级行业'),
        ),
    ]
