# Generated by Django 2.2.11 on 2020-04-28 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacenter', '0014_auto_20200428_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='total',
            name='linked_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='关联客户ID'),
        ),
    ]
