# Generated by Django 2.2.11 on 2020-09-17 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacenter', '0036_auto_20200709_0951'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日期')),
                ('userid', models.CharField(max_length=16, verbose_name='账户ID')),
                ('company_name', models.CharField(blank=True, max_length=128, null=True, verbose_name='公司名称')),
                ('depart', models.CharField(blank=True, max_length=64, null=True, verbose_name='部门')),
                ('frame1', models.CharField(max_length=64, verbose_name='一级架构')),
                ('frame2', models.CharField(max_length=64, verbose_name='二级架构')),
                ('frame3', models.CharField(max_length=64, verbose_name='三级架构')),
                ('frame4', models.CharField(max_length=64, verbose_name='四级架构')),
            ],
            options={
                'verbose_name': '开户消费',
                'verbose_name_plural': '开户消费',
                'ordering': ['-date'],
            },
        ),
    ]
