# Generated by Django 2.2.11 on 2020-09-18 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacenter', '0037_personal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personal',
            options={'get_latest_by': 'date', 'ordering': ['-date'], 'verbose_name': '开户消费', 'verbose_name_plural': '开户消费'},
        ),
        migrations.AddField(
            model_name='personal',
            name='sign_date',
            field=models.DateField(default='2020-08-01', verbose_name='计入日期'),
            preserve_default=False,
        ),
    ]
