# Generated by Django 2.2.11 on 2021-01-18 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacenter', '0040_auto_20200921_1046'),
    ]

    operations = [
        migrations.CreateModel(
            name='KAPersonal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日期')),
                ('userid', models.CharField(max_length=16, verbose_name='账户ID')),
                ('username', models.CharField(max_length=128, verbose_name='账户名称')),
                ('company_name', models.CharField(blank=True, max_length=128, null=True, verbose_name='公司名称')),
                ('depart', models.CharField(blank=True, max_length=64, null=True, verbose_name='部门')),
                ('frame1', models.CharField(max_length=64, verbose_name='一级架构')),
                ('frame2', models.CharField(blank=True, max_length=64, null=True, verbose_name='二级架构')),
                ('frame3', models.CharField(blank=True, max_length=64, null=True, verbose_name='三级架构')),
                ('sf_name', models.CharField(max_length=64, verbose_name='SF二级账号')),
            ],
            options={
                'verbose_name': 'KA商务新户消费',
                'verbose_name_plural': 'KA商务新户消费',
                'ordering': ['-date'],
                'get_latest_by': 'date',
            },
        ),
        migrations.AlterModelOptions(
            name='personal',
            options={'get_latest_by': 'date', 'ordering': ['-date'], 'verbose_name': '商务新户消费', 'verbose_name_plural': '商务新户消费'},
        ),
    ]
