# Generated by Django 2.2.11 on 2021-03-09 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datacenter', '0041_auto_20210118_1655'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kapersonal',
            options={'get_latest_by': 'date', 'ordering': ['-date'], 'verbose_name': 'KA商务消费监控', 'verbose_name_plural': 'KA商务消费监控'},
        ),
    ]
