# Generated by Django 2.2.11 on 2021-03-23 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datacenter', '0042_auto_20210309_1802'),
    ]

    operations = [
        migrations.CreateModel(
            name='MEGIndustry1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meg_indus1_name', models.CharField(max_length=16, unique=True, verbose_name='MEG一级行业')),
            ],
            options={
                'verbose_name': 'MEG一级行业',
                'verbose_name_plural': 'MEG一级行业',
            },
        ),
        migrations.CreateModel(
            name='MEGIndustry2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meg_indus2_name', models.CharField(max_length=16, unique=True, verbose_name='MEG二级行业')),
                ('meg_indus1_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datacenter.MEGIndustry1', verbose_name='MEG一级行业')),
            ],
            options={
                'verbose_name': 'MEG二级行业',
                'verbose_name_plural': 'MEG二级行业',
            },
        ),
    ]
