# Generated by Django 2.2.11 on 2020-06-01 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AreaData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日期')),
                ('userid', models.CharField(max_length=16, verbose_name='账户ID')),
                ('username', models.CharField(max_length=64, verbose_name='账户名称')),
                ('indus_1', models.CharField(max_length=32, verbose_name='一级行业')),
                ('indus_2', models.CharField(max_length=32, verbose_name='二级行业')),
                ('sf_name', models.CharField(max_length=32, verbose_name='SF二级账号')),
                ('depart_1', models.CharField(max_length=32, verbose_name='一级部门')),
                ('depart_2', models.CharField(max_length=32, verbose_name='二级部门')),
                ('depart_3', models.CharField(max_length=32, verbose_name='三级部门')),
                ('area1', models.CharField(max_length=32, verbose_name='一级地域')),
                ('area2', models.CharField(max_length=32, verbose_name='二级地域')),
                ('consume', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='消费')),
                ('click', models.IntegerField(max_length=10, verbose_name='点击')),
                ('pv', models.IntegerField(max_length=10, verbose_name='展现')),
            ],
            options={
                'verbose_name': '推广地域分布',
                'verbose_name_plural': '推广地域分布',
            },
        ),
        migrations.CreateModel(
            name='HourData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日期')),
                ('hour', models.IntegerField(max_length=4, verbose_name='时段')),
                ('userid', models.CharField(max_length=16, verbose_name='账户ID')),
                ('username', models.CharField(max_length=64, verbose_name='账户名称')),
                ('indus_1', models.CharField(max_length=32, verbose_name='一级行业')),
                ('indus_2', models.CharField(max_length=32, verbose_name='二级行业')),
                ('sf_name', models.CharField(max_length=32, verbose_name='SF二级账号')),
                ('depart_1', models.CharField(max_length=32, verbose_name='一级部门')),
                ('depart_2', models.CharField(max_length=32, verbose_name='二级部门')),
                ('depart_3', models.CharField(max_length=32, verbose_name='三级部门')),
                ('consume', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='消费')),
                ('click', models.IntegerField(max_length=10, verbose_name='点击')),
                ('pv', models.IntegerField(max_length=10, verbose_name='展现')),
            ],
            options={
                'verbose_name': '推广时段分布',
                'verbose_name_plural': '推广时段分布',
            },
        ),
        migrations.CreateModel(
            name='KeyWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日期')),
                ('userid', models.CharField(max_length=16, verbose_name='账户ID')),
                ('username', models.CharField(max_length=64, verbose_name='账户名称')),
                ('indus_1', models.CharField(max_length=32, verbose_name='一级行业')),
                ('indus_2', models.CharField(max_length=32, verbose_name='二级行业')),
                ('sf_name', models.CharField(max_length=32, verbose_name='SF二级账号')),
                ('depart_1', models.CharField(max_length=32, verbose_name='一级部门')),
                ('depart_2', models.CharField(max_length=32, verbose_name='二级部门')),
                ('depart_3', models.CharField(max_length=32, verbose_name='三级部门')),
                ('keyword', models.CharField(max_length=128, verbose_name='关键词')),
                ('consume', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='消费')),
                ('click', models.IntegerField(max_length=10, verbose_name='点击')),
                ('pv', models.IntegerField(max_length=10, verbose_name='展现')),
            ],
            options={
                'verbose_name': '关键词数据',
                'verbose_name_plural': '关键词数据',
            },
        ),
        migrations.CreateModel(
            name='NewCompany',
            fields=[
                ('companyName', models.CharField(max_length=128, verbose_name='公司名称')),
                ('identifier', models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name='统一社会信用代码')),
                ('date', models.DateField(verbose_name='注册日期')),
                ('location', models.CharField(max_length=32, verbose_name='注册地点')),
                ('founder', models.CharField(max_length=32, verbose_name='法人代表')),
                ('registerMoney', models.CharField(max_length=32, verbose_name='注册资金')),
                ('address', models.CharField(max_length=512, verbose_name='注册地址')),
                ('companyType', models.CharField(max_length=32, verbose_name='企业类型')),
                ('companyStatus', models.CharField(max_length=16, verbose_name='经营状态')),
                ('makesOffer', models.CharField(max_length=1024, verbose_name='经营范围')),
            ],
            options={
                'verbose_name': '新注册公司数据',
                'verbose_name_plural': '新注册公司数据',
            },
        ),
    ]
