# Generated by Django 2.2.11 on 2020-06-01 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apidata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areadata',
            name='click',
            field=models.IntegerField(verbose_name='点击'),
        ),
        migrations.AlterField(
            model_name='areadata',
            name='pv',
            field=models.IntegerField(verbose_name='展现'),
        ),
        migrations.AlterField(
            model_name='hourdata',
            name='click',
            field=models.IntegerField(verbose_name='点击'),
        ),
        migrations.AlterField(
            model_name='hourdata',
            name='pv',
            field=models.IntegerField(verbose_name='展现'),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='click',
            field=models.IntegerField(verbose_name='点击'),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='pv',
            field=models.IntegerField(verbose_name='展现'),
        ),
    ]
