# Generated by Django 2.2.11 on 2020-06-01 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apidata', '0003_auto_20200601_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areadata',
            name='sf_name',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='SF二级账号'),
        ),
        migrations.AlterField(
            model_name='hourdata',
            name='sf_name',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='SF二级账号'),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='sf_name',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='SF二级账号'),
        ),
    ]
