# Generated by Django 2.2.11 on 2020-06-04 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apidata', '0004_auto_20200601_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hourdata',
            name='hour',
            field=models.IntegerField(max_length=4, verbose_name='时段'),
        ),
    ]
