# Generated by Django 2.2.11 on 2020-06-04 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apidata', '0005_auto_20200604_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hourdata',
            name='hour',
            field=models.IntegerField(verbose_name='时段'),
        ),
    ]
