# Generated by Django 2.2.11 on 2020-06-05 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apidata', '0006_auto_20200604_1145'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newcompany',
            options={'get_latest_by': 'date', 'verbose_name': '新注册公司数据', 'verbose_name_plural': '新注册公司数据'},
        ),
    ]
