# Generated by Django 2.2.11 on 2020-06-05 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apidata', '0008_auto_20200605_1522'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newcompany',
            options={'ordering': ['-date'], 'verbose_name': '新注册公司数据', 'verbose_name_plural': '新注册公司数据'},
        ),
    ]
