# Generated by Django 2.2.11 on 2020-06-11 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apidata', '0011_auto_20200610_1809'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='areadata',
            options={'get_latest_by': 'date', 'verbose_name': '推广地域分布', 'verbose_name_plural': '推广地域分布'},
        ),
        migrations.AlterModelOptions(
            name='hourdata',
            options={'get_latest_by': 'date', 'verbose_name': '推广时段分布', 'verbose_name_plural': '推广时段分布'},
        ),
        migrations.AlterModelOptions(
            name='keyword',
            options={'get_latest_by': 'date', 'verbose_name': '关键词数据', 'verbose_name_plural': '关键词数据'},
        ),
    ]
