# Generated by Django 2.2.11 on 2021-03-24 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apidata', '0013_searchword'),
    ]

    operations = [
        migrations.AddField(
            model_name='newcompany',
            name='province',
            field=models.CharField(default='湖北', max_length=64, verbose_name='注册省'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='newcompany',
            name='location',
            field=models.CharField(max_length=64, verbose_name='注册市'),
        ),
    ]
