# Generated by Django 2.2.11 on 2020-07-16 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0013_message_is_jump'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='is_jump',
            field=models.BooleanField(default=False, help_text='意思是输入跳转链接还是描述内容', verbose_name='是否跳转'),
        ),
    ]
