# Generated by Django 2.2.11 on 2020-07-16 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0014_auto_20200716_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(verbose_name='内容'),
        ),
    ]
