# Generated by Django 2.2.11 on 2020-07-17 01:00

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0015_auto_20200716_1450'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='is_jump',
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='内容'),
        ),
    ]
