# Generated by Django 2.2.11 on 2020-07-17 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0017_auto_20200717_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='is_jump',
            field=models.BooleanField(default=False, help_text='输入跳转链接还是描述内容', verbose_name='是否跳转'),
        ),
    ]
