# Generated by Django 2.2.11 on 2020-07-23 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0018_auto_20200717_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='is_jump',
            field=models.BooleanField(default=False, help_text='勾选，输入链接，去掉勾选，输入文本', verbose_name='是否跳转'),
        ),
    ]
