# Generated by Django 2.2.11 on 2020-08-31 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0019_auto_20200723_1150'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='标题')),
                ('status', models.PositiveIntegerField(choices=[(1, '显示'), (0, '不显示')], default=1, help_text='默认显示', verbose_name='是否显示')),
                ('img', models.ImageField(upload_to='banners/', verbose_name='上传图片')),
                ('created_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '主页Banner图片',
                'verbose_name_plural': '主页Banner图片',
                'ordering': ['-created_time'],
            },
        ),
    ]
