# Generated by Django 2.2.11 on 2020-06-19 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peixuncenter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourceinfo',
            name='desc',
            field=models.CharField(blank=True, help_text='选填', max_length=128, null=True, verbose_name='描述'),
        ),
    ]
