# Generated by Django 2.2.11 on 2020-06-28 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peixuncenter', '0006_sharefile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShareCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='分类名称')),
                ('status', models.PositiveIntegerField(choices=[(1, '显示'), (0, '不显示')], default=1, verbose_name='状态')),
                ('created_time', models.DateField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '资讯分类',
                'verbose_name_plural': '资讯分类',
            },
        ),
        migrations.AlterModelOptions(
            name='sharefile',
            options={'ordering': ['-created_time'], 'verbose_name': '资讯速分享', 'verbose_name_plural': '资讯速分享'},
        ),
        migrations.AlterField(
            model_name='resourceinfo',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='文章链接'),
        ),
        migrations.AddField(
            model_name='sharefile',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='peixuncenter.ShareCategory', verbose_name='资讯分类'),
            preserve_default=False,
        ),
    ]
