# Generated by Django 2.2.11 on 2020-06-28 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peixuncenter', '0008_auto_20200628_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourceinfo',
            name='link',
            field=models.URLField(blank=True, help_text='选填', null=True, verbose_name='小鹅通链接'),
        ),
    ]
