# Generated by Django 2.2.11 on 2020-06-29 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peixuncenter', '0009_auto_20200628_1759'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resourceinfo',
            options={'ordering': ['-is_top', '-created_time'], 'verbose_name': '培训资源', 'verbose_name_plural': '培训资源'},
        ),
        migrations.AddField(
            model_name='resourceinfo',
            name='is_top',
            field=models.PositiveIntegerField(choices=[(1, '置顶'), (0, '不置顶')], default=0, help_text='默认不置顶', verbose_name='是否置顶'),
        ),
    ]
