# Generated by Django 2.2.11 on 2020-06-29 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peixuncenter', '0010_auto_20200629_1028'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sharefile',
            options={'ordering': ['-is_top', '-created_time'], 'verbose_name': '资讯速分享', 'verbose_name_plural': '资讯速分享'},
        ),
        migrations.AddField(
            model_name='sharefile',
            name='is_top',
            field=models.PositiveIntegerField(choices=[(1, '置顶'), (0, '不置顶')], default=0, help_text='默认不置顶', verbose_name='是否置顶'),
        ),
    ]
