# Generated by Django 2.2.11 on 2020-06-30 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peixuncenter', '0011_auto_20200629_1137'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoryinfo',
            options={'ordering': ['-created_time'], 'verbose_name': '培训资源分类', 'verbose_name_plural': '培训资源分类'},
        ),
        migrations.AlterModelOptions(
            name='sharecategory',
            options={'ordering': ['-created_time'], 'verbose_name': '资讯分类', 'verbose_name_plural': '资讯分类'},
        ),
        migrations.AlterField(
            model_name='categoryinfo',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='resourceinfo',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='sharecategory',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='sharefile',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
    ]
